spring:
  datasource:
    url: jdbc:mysql://localhost:3306/url-shortener
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      add-mappings: false

urlshorten:
  schedule:
    expireSchedule: 600000